from .login import Login as LoginResource
from .signIn import SignIn as SignInResource
from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .libro import Libro as LibroResource
from .libro import Libros as LibrosResource
from .prestamo import Prestamo as PrestamoResource
from .prestamo import Prestamos as PrestamosResource
from .notificacion import Notificacion as NotifacionResource
from .autor import Autor as AutorResource
from .autor import Autores as AutoresResource
from .reseña import Reseña as ReseñaResource
from .reseña import Reseñas as ReseñasResource