from .login import Login as LoginResource
from .singIn import SignIn as SignInResource
from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .libro import Libro as LibroResource
from .libro import Libros as LibrosResourse
from .prestamo import Prestamo as PrestamoResourse
from .prestamo import Prestamos as PrestamosResourse
from .comentario import Comentario as ComentarioResource
from .comentario import Comentarios as ComentariosResource
from .valoracion import Valoracion as ValoracionResourse
from .valoracion import Valoraciones as ValoracionesResourse
from .notificacion import Notificacion as NotifacionResourse
